stages:
  - build
  - deploy

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - export TASKWOLF_GITLAB_PRIVATE_TOKEN="$TASKWOLF_GITLAB_PRIVATE_TOKEN"

build:
  stage: build
  image: openjdk:21
  artifacts:
    paths:
      - build/libs/core-1.0.0-SNAPSHOT.jar
    expire_in: 1 day
  script:
    - ./gradlew assemble